# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-cls-deployment
spec:
  replicas: 1  # Number of pods
  # Selector and template define how to find/create Pods
  selector:
    matchLabels:
      app: cancer-cls
  template:
    metadata:
      labels:
        app: cancer-cls
    spec:
      containers:
      - name: cancer-cls-container
        image: 835754295871.dkr.ecr.us-east-1.amazonaws.com/cancer-cls:latest
        ports:
        - name: http
          containerPort: 8000
        envFrom:
        - secretRef:
            name: cancer-cls-secrets # Reference to the Kubernetes Secret
...
---
apiVersion: v1
kind: Service
metadata:
  name: cancer-cls-service
spec:
  type: LoadBalancer
  selector:
    app: cancer-cls-selctor
  ports:
    - name: http
      port: 80 #  Service is accessed on port 80
      targetPort: 8000  # Traffic forwarded to port 8000 on the pod
