# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - _self_ # Include the rest of this file's content

hydra:
  # mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  # optuna hyperparameter search
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: ${logger.experiment_name}
    storage: null
    n_trials: 5
    n_jobs: 1

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      n_startup_trials: 5 # number of random sampling runs before optimization starts
    # pruner:
    #     _target_: optuna.pruners.MedianPruner
    params:
      datamodule.batch_size: choice(32, 64, 128, 256)
      model.net.conv_layers: range(2, 7) # Corresponds to 'total_conv_layers'
      model.net.num_hidden_layers: range(1, 7) # Corresponds to 'total_cls_hidden_layers'
      model.net.dropout_rate: range(0.1, 0.5, 0.1) # Corresponds to 'dropout_rate'
