_target_: src.model.lung_colon_cancer_classifier.LungColonCancerClassifier
defaults:
  - default
  - net: custom_conv_net
is_compile: true
class_names:
  [
    "colon-adenocarcinoma",
    "colon-benign-tissue",
    "lung-adenocarcinoma",
    "lung-benign-tissue",
    "lung-squamous-cell-carcinoma",
  ]
