__target__: src/model/lung_colon_cancer_classifier
defaults:
  - defaults
  - net: custom_conv_net

class_names:
  [
    "colon-adenocarcinoma",
    "colon-benign-tissue",
    "lung-adenocarcinoma",
    "lung-benign-tissue",
    "lung-squamous-cell-carcinoma",
  ]
#  optimizer  and scheduler will be taken from defaults
