defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: ${monitor_metric}
  mode: ${monitor_direction}
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: ${monitor_metric}
  patience: 3
  mode: ${monitor_direction}

model_summary:
  max_depth: -1
