# For Dataloader
batch_size: 32
num_workers: 8
# shuffle is already set in the dataloader
pin_memory: True
persistent_workers: True
train_processed_dir: ${paths.train_processed_dir}
valid_processed_dir: ${paths.valid_processed_dir}
test_processed_dir: ${paths.test_processed_dir}
subset_size: null
